title: Daryn Mann - ePortfolio
description: CS499 Capstone Assessment & Artifact Enhancements
baseurl: ""
url: "https://superluminalspin.github.io"
markdown: kramdown
theme: minima

# Optional: Add your social links
github_username: superluminalspin
linkedin_username: _________
email: daryn.mann@snhu.edu
